#!/bin/sh

#~ ❯ bluetoothctl -- connect F8:8F:07:36:B1:1B
#~ ❯ bluetoothctl -- disconnect F8:8F:07:36:B1:1B
connected_devices=$(bluetoothctl -- devices Connected)

if [ ! -z "$connected_devices" ]; then
    case $BLOCK_BUTTON in
	    1) notify-send -t 4000 "$connected_devices" ;;
    esac

	echo ""
fi