#!/bin/sh

icon='聆'

pidof /usr/lib/slack/slack > /dev/null
if [ $? -eq 0 ]; then

    case $BLOCK_BUTTON in
	    1) slack > /dev/null ;;
        3) notify-send -t 4000 "Slack" "Slack is active" ;;
    esac

    echo "$icon"
fi
